name: phone_util
description: A flutter package to select a country from a list of countries.

version: 0.0.1

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # TODO: Отказаться от этой зависимости
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
